// Package config provides application configuration loaded from environment variables.
package config

import (
	"fmt"
	"os"
	"strconv"
	"strings"
)

// Config holds all configuration values for the builder-svc service.
type Config struct {
	// Port is the HTTP listen port for the API process.
	Port string
	// BuildKitHost is the gRPC address of the BuildKit daemon.
	BuildKitHost string
	// WorkdirRoot is the base directory for per-build temporary workspaces.
	WorkdirRoot string
	// MaxRepoSizeMB is the maximum allowed cloned repository size in megabytes.
	MaxRepoSizeMB int64
	// MaxBuildTimeMin is the maximum allowed build time in minutes.
	MaxBuildTimeMin int
	// MaxConcurrentBuildsPerUser limits how many builds a single user can have in-flight.
	MaxConcurrentBuildsPerUser int
	// AllowedGitHosts is the list of permitted Git hosting domains.
	AllowedGitHosts []string
	// AllowedBaseImagePrefixes is the list of permitted Docker base image prefixes.
	AllowedBaseImagePrefixes []string
	// AllowedBaseImagePrefixesPermissive is the wider allow-list applied
	// when the Dockerfile was provided by the repo author (vs generated by
	// our LLM). Sourced from ALLOWED_BASE_IMAGES_PERMISSIVE env var. If
	// empty, falls back to AllowedBaseImagePrefixes (i.e. strict mode for
	// everything).
	AllowedBaseImagePrefixesPermissive []string
	// WebhookSecret is the shared secret for authenticating service-to-service calls.
	WebhookSecret string
	// AIOrchestratorURL is the HTTP endpoint for the AI Dockerfile generator.
	AIOrchestratorURL string
	// UserBillingURL is the HTTP endpoint for the user-billing service.
	UserBillingURL string
	// MaxArchiveFiles caps entries extracted from an uploaded archive
	// (source_type=archive, Task 14b-2).
	MaxArchiveFiles int
	// MaxArchiveFileMB caps a single extracted file's uncompressed size.
	MaxArchiveFileMB int
	// MaxArchiveTotalMB caps the total uncompressed size of an archive.
	MaxArchiveTotalMB int
}

// Load reads configuration from environment variables with fallback to defaults.
// Required fields without defaults cause an error if unset.
func Load() (*Config, error) {
	cfg := &Config{
		Port:              envOrDefault("PORT", "8082"),
		BuildKitHost:      envOrDefault("BUILDKIT_HOST", "tcp://buildkitd:1234"),
		WorkdirRoot:       envOrDefault("WORKDIR_ROOT", "/var/snaphost/builds"),
		AIOrchestratorURL: envOrDefault("AI_ORCHESTRATOR_URL", "http://ai-orchestrator:8087"),
		UserBillingURL:    envOrDefault("USER_BILLING_URL", "http://user-billing:8081"),
	}

	// Required: WEBHOOK_SECRET
	cfg.WebhookSecret = os.Getenv("WEBHOOK_SECRET")
	if cfg.WebhookSecret == "" {
		return nil, fmt.Errorf("config: WEBHOOK_SECRET is required but not set")
	}

	// MaxRepoSizeMB
	maxRepoStr := envOrDefault("MAX_REPO_SIZE_MB", "500")
	maxRepo, err := strconv.ParseInt(maxRepoStr, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("config: MAX_REPO_SIZE_MB is not a valid integer: %w", err)
	}
	cfg.MaxRepoSizeMB = maxRepo

	// MaxBuildTimeMin
	maxBuildStr := envOrDefault("MAX_BUILD_TIME_MIN", "15")
	maxBuild, err := strconv.Atoi(maxBuildStr)
	if err != nil {
		return nil, fmt.Errorf("config: MAX_BUILD_TIME_MIN is not a valid integer: %w", err)
	}
	cfg.MaxBuildTimeMin = maxBuild

	// MaxConcurrentBuildsPerUser
	maxConcStr := envOrDefault("MAX_CONCURRENT_PER_USER", "3")
	maxConc, err := strconv.Atoi(maxConcStr)
	if err != nil {
		return nil, fmt.Errorf("config: MAX_CONCURRENT_PER_USER is not a valid integer: %w", err)
	}
	cfg.MaxConcurrentBuildsPerUser = maxConc

	// Archive unpack limits (source_type=archive, Task 14b-2).
	maxArchiveFilesStr := envOrDefault("MAX_ARCHIVE_FILES", "5000")
	maxArchiveFiles, err := strconv.Atoi(maxArchiveFilesStr)
	if err != nil {
		return nil, fmt.Errorf("config: MAX_ARCHIVE_FILES is not a valid integer: %w", err)
	}
	cfg.MaxArchiveFiles = maxArchiveFiles

	maxArchiveFileStr := envOrDefault("MAX_ARCHIVE_FILE_MB", "50")
	maxArchiveFile, err := strconv.Atoi(maxArchiveFileStr)
	if err != nil {
		return nil, fmt.Errorf("config: MAX_ARCHIVE_FILE_MB is not a valid integer: %w", err)
	}
	cfg.MaxArchiveFileMB = maxArchiveFile

	maxArchiveTotalStr := envOrDefault("MAX_ARCHIVE_TOTAL_MB", "200")
	maxArchiveTotal, err := strconv.Atoi(maxArchiveTotalStr)
	if err != nil {
		return nil, fmt.Errorf("config: MAX_ARCHIVE_TOTAL_MB is not a valid integer: %w", err)
	}
	cfg.MaxArchiveTotalMB = maxArchiveTotal

	// AllowedGitHosts
	hostsStr := envOrDefault("ALLOWED_GIT_HOSTS", "github.com,gitlab.com,bitbucket.org")
	cfg.AllowedGitHosts = splitTrim(hostsStr, ",")

	// AllowedBaseImagePrefixes
	imagesStr := envOrDefault("ALLOWED_BASE_IMAGES", "node:,python:,golang:,ruby:,nginx:,alpine:,debian:,ubuntu:,gcr.io/distroless/,oven/bun:,denoland/deno:")
	cfg.AllowedBaseImagePrefixes = splitTrim(imagesStr, ",")

	// Permissive list. Empty env means "use strict for everything" — that
	// preserves pre-9.3 behaviour for clusters that haven't set the env yet.
	permImagesStr := os.Getenv("ALLOWED_BASE_IMAGES_PERMISSIVE")
	if strings.TrimSpace(permImagesStr) == "" {
		cfg.AllowedBaseImagePrefixesPermissive = cfg.AllowedBaseImagePrefixes
	} else {
		cfg.AllowedBaseImagePrefixesPermissive = splitTrim(permImagesStr, ",")
	}

	return cfg, nil
}

// envOrDefault returns the value of the named environment variable or the
// provided fallback if the variable is empty or unset.
func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// splitTrim splits s by sep and trims whitespace from each element.
func splitTrim(s, sep string) []string {
	parts := strings.Split(s, sep)
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}
